// Magic Stack — contribution form.
// Reads forms.json (generated by build.lua) and renders the form for the
// page the reader came from: contribute.html?book=<id>&page=<id>&seg=<anchor>
// Everything the reader typed is inserted with textContent, never as HTML.

(function () {
  "use strict";

  const app = document.getElementById("app");
  const params = new URLSearchParams(location.search);
  const CONSENTS = ["terms", "original", "adult", "future", "data"];

  let F, book, page, lang, tplId, seg, turnstileId = null;

  // ---------- tiny helpers ----------
  function el(tag, attrs, ...kids) {
    const n = document.createElement(tag);
    for (const [k, v] of Object.entries(attrs || {})) {
      if (v === false || v == null) continue;
      if (k === "class") n.className = v;
      else if (k === "text") n.textContent = v;
      else if (k.startsWith("on")) n.addEventListener(k.slice(2), v);
      else n.setAttribute(k, v === true ? "" : v);
    }
    for (const kid of kids.flat()) if (kid != null) n.append(kid);
    return n;
  }
  const t = (key) => {
    const s = F.strings[key];
    return s ? (s[lang] || s.en).replace("{v}", F.site.terms_version) : key;
  };
  const tx = (obj) => (typeof obj === "string" ? obj : obj ? obj[lang] || obj.en : "");
  const store = {
    get(k) { try { return JSON.parse(localStorage.getItem(k)); } catch (e) { return null; } },
    set(k, v) { try { localStorage.setItem(k, JSON.stringify(v)); } catch (e) { /* private mode */ } },
    del(k) { try { localStorage.removeItem(k); } catch (e) { /* ignore */ } },
  };
  const draftKey = () => `ms-draft:${book.id}:${page.id}:${tplId}`;
  const template = () => (book.templates && book.templates[tplId]) || F.templates[tplId];
  const canSend = () => Boolean(F.site.worker_url) && book.open;

  // ---------- boot ----------
  fetch("forms.json", { cache: "no-cache" })
    .then((r) => { if (!r.ok) throw new Error(r.status); return r.json(); })
    .then((data) => { F = data; start(); })
    .catch(() => { app.textContent = "The form could not be loaded. Please reload the page."; });

  function start() {
    const bookId = params.get("book"), pageId = params.get("page");
    const b = F.books[bookId];
    const p = b && b.pages[pageId];
    // the site-wide language (switch at the top right); see shelf/lang-head.html
    lang = window.msLang ? window.msLang() : (params.get("lang") || F.site.default_lang);
    if (!F.site.langs.includes(lang)) lang = F.site.default_lang;
    if (!b || !p || !p.templates.length) {
      app.replaceChildren(el("div", { class: "notice" },
        el("p", { text: t("not_found") }), el("p", {}, el("a", { href: "index.html", text: "← " + t("shelf") }))));
      return;
    }
    book = Object.assign({ id: bookId }, b);
    page = Object.assign({ id: pageId }, p);
    const wanted = params.get("tpl");
    tplId = page.templates.includes(wanted) ? wanted : page.templates[0];
    const s = params.get("seg");
    seg = segs().some((x) => x.id === s) ? s : "";
    document.addEventListener("ms:lang", (e) => {
      saveDraft();
      const before = segs().findIndex((x) => x.id === seg);
      lang = e.detail;
      // the same section has a different anchor in each language: keep its position
      seg = before >= 0 && segs()[before] ? segs()[before].id : "";
      render();
    });
    render();
  }

  const segs = () => (Array.isArray(page.segments) ? page.segments : (page.segments[lang] || []));
  const backHref = () => `${book.id}/${lang}/${page.id}.html${seg ? "#" + seg : ""}`;

  // ---------- render ----------
  function render() {
    document.documentElement.lang = lang;
    const tpl = template();
    const back = backHref();

    const segSelect = el("select", { id: "f-seg", onchange: (e) => { seg = e.target.value; } },
      el("option", { value: "", text: t("whole_page") }),
      segs().map((s) => el("option", { value: s.id, text: s.title, selected: s.id === seg })));

    const head = el("header", { class: "form-head" },
      el("div", { class: "form-head-top" },
        el("a", { class: "back", href: back, text: "← " + t("sent_back") })),
      el("p", { class: "kicker", text: `${t("contribute_to")} · ${tx(book.title)}` }),
      el("h1", { text: tx(page.title) }),
      el("div", { class: "where" },
        el("label", { for: "f-seg", text: t("segment") }), segSelect));

    let chooser = null;
    if (page.templates.length > 1) {
      chooser = el("fieldset", { class: "chooser" },
        el("legend", { text: t("choose_form") }),
        page.templates.map((id) => {
          const tp = (book.templates && book.templates[id]) || F.templates[id];
          return el("label", { class: "choice" + (id === tplId ? " on" : "") },
            el("input", { type: "radio", name: "tpl", value: id, checked: id === tplId,
              onchange: () => { saveDraft(); tplId = id; render(); } }),
            el("strong", { text: tx(tp.title) }), el("span", { text: tx(tp.intro) }));
        }));
    }

    const form = el("form", { class: "contrib-form", novalidate: true, onsubmit: submit });
    if (!canSend()) {
      form.append(el("div", { class: "notice closed", role: "note" },
        el("strong", { text: t("closed_title") }), el("p", { text: t("closed_body") })));
    }
    form.append(el("h2", { text: tx(tpl.title) }));
    if (!chooser) form.append(el("p", { class: "intro", text: tx(tpl.intro) }));
    for (const f of tpl.fields) form.append(fieldRow(f));

    // about you
    form.append(el("h2", { text: t("about_you") }));
    form.append(fieldRow({ id: "c_name", type: "text", required: true, max: 120, label: F.strings.name }));
    form.append(fieldRow({ id: "c_email", type: "email", required: true, max: 200, label: F.strings.email, help: F.strings.email_help }));
    const modes = [["name", "credit_name_opt"], ["pseudonym", "credit_pseudo"], ["anonymous", "credit_anon"]];
    const pseudoRow = fieldRow({ id: "c_credit_name", type: "text", max: 80, label: F.strings.credit_name });
    form.append(el("fieldset", { class: "radios", id: "c_credit_mode" },
      el("legend", { text: t("credit_mode") }),
      modes.map(([v, key], i) => el("label", {},
        el("input", { type: "radio", name: "c_credit_mode", value: v, checked: i === 0,
          onchange: () => { pseudoRow.hidden = v !== "pseudonym"; } }),
        " " + t(key)))));
    pseudoRow.hidden = true;
    form.append(pseudoRow);

    // consent
    form.append(el("h2", { text: t("consent") }));
    const consent = el("fieldset", { class: "consent", id: "consent" }, el("legend", { class: "sr", text: t("consent") }));
    for (const c of CONSENTS) {
      const label = el("label", {}, el("input", { type: "checkbox", name: "consent_" + c, required: true }), " ", t("consent_" + c));
      if (c === "terms") label.append(" ", el("a", { href: F.site.terms_url + (lang === "pt" ? "#pt" : "#en"), target: "_blank", rel: "noopener", text: t("read_terms") + " ↗" }));
      consent.append(label);
    }
    form.append(consent);

    // honeypot: humans never see or fill it
    form.append(el("div", { class: "hp", "aria-hidden": "true" },
      el("label", {}, "Website", el("input", { type: "text", name: "website", tabindex: "-1", autocomplete: "off" }))));

    const ts = el("div", { id: "turnstile", class: "turnstile" });
    form.append(ts);
    form.append(el("p", { class: "form-error", id: "form-error", role: "alert" }));
    form.append(el("div", { class: "actions" },
      el("button", { class: "btn", type: "submit", disabled: !canSend(), text: t("send") }),
      el("span", { class: "saved", id: "saved" })));

    app.replaceChildren(head, chooser || "", form);
    restoreDraft(form);
    form.addEventListener("input", debounce(saveDraft, 600));

    if (canSend() && F.site.turnstile_sitekey) {
      const mount = () => {
        if (window.turnstile) {
          turnstileId = window.turnstile.render(ts, { sitekey: F.site.turnstile_sitekey, language: lang, theme: "dark" });
        } else setTimeout(mount, 300);
      };
      mount();
    }
  }

  function fieldRow(f) {
    const id = "f-" + f.id;
    const req = Boolean(f.required);
    const label = el("label", { for: id },
      tx(f.label), " ", el("span", { class: req ? "req" : "opt", text: req ? "*" : `(${t("optional")})` }));
    let input;
    if (f.type === "textarea") {
      input = el("textarea", { id, name: f.id, rows: f.max > 2500 ? 9 : f.max > 1200 ? 6 : 4, maxlength: f.max, required: req });
    } else if (f.type === "select") {
      input = el("select", { id, name: f.id, required: req },
        el("option", { value: "", text: "—" }),
        f.options.map((o) => el("option", { value: o.value, text: tx(o.label) })));
    } else {
      const type = f.type === "url" ? "url" : f.type === "number" ? "number" : f.type === "email" ? "email" : "text";
      input = el("input", { id, name: f.id, type, maxlength: f.max, required: req, min: f.min, max: f.type === "number" ? f.max : null,
        autocomplete: f.id === "c_name" ? "name" : f.id === "c_email" ? "email" : "off" });
    }
    const kids = [label];
    if (f.help) kids.push(el("p", { class: "help", id: id + "-help", text: tx(f.help) }));
    kids.push(input);
    if (f.help) input.setAttribute("aria-describedby", id + "-help");
    if (f.type === "textarea" && f.max) {
      const counter = el("p", { class: "count", "aria-live": "off" });
      const upd = () => { counter.textContent = `${f.max - input.value.length} ${t("chars_left")}`; };
      input.addEventListener("input", upd); upd();
      kids.push(counter);
    }
    kids.push(el("p", { class: "field-error", id: id + "-err" }));
    return el("div", { class: "row", "data-field": f.id }, kids);
  }

  // ---------- drafts ----------
  function collect(form) {
    const fd = new FormData(form || app.querySelector("form"));
    const fields = {};
    for (const f of template().fields) fields[f.id] = (fd.get(f.id) || "").toString().trim();
    return {
      fields,
      contributor: {
        name: (fd.get("c_name") || "").toString().trim(),
        email: (fd.get("c_email") || "").toString().trim(),
        credit_mode: (fd.get("c_credit_mode") || "name").toString(),
        credit_name: (fd.get("c_credit_name") || "").toString().trim(),
      },
      website: (fd.get("website") || "").toString(),
    };
  }
  function saveDraft() {
    const form = app.querySelector("form.contrib-form");
    if (!form) return;
    const d = collect(form);
    store.set(draftKey(), { fields: d.fields, contributor: d.contributor, seg });
    store.set("ms-contributor", d.contributor);
    const s = document.getElementById("saved");
    if (s) s.textContent = t("draft_saved");
  }
  function restoreDraft(form) {
    const d = store.get(draftKey()) || {};
    const who = d.contributor || store.get("ms-contributor") || {};
    for (const [k, v] of Object.entries(d.fields || {})) if (form.elements[k] && v) form.elements[k].value = v;
    if (who.name) form.elements.c_name.value = who.name;
    if (who.email) form.elements.c_email.value = who.email;
    if (who.credit_name) form.elements.c_credit_name.value = who.credit_name;
    if (who.credit_mode) {
      const r = form.querySelector(`input[name=c_credit_mode][value="${who.credit_mode}"]`);
      if (r) { r.checked = true; document.querySelector('[data-field="c_credit_name"]').hidden = who.credit_mode !== "pseudonym"; }
    }
    form.querySelectorAll("textarea").forEach((x) => x.dispatchEvent(new Event("input")));
  }
  function debounce(fn, ms) { let h; return () => { clearTimeout(h); h = setTimeout(fn, ms); }; }

  // ---------- submit ----------
  function showError(fieldId, msg) {
    const e = document.getElementById("f-" + fieldId + "-err");
    if (e) e.textContent = msg;
    const inp = document.getElementById("f-" + fieldId);
    if (inp) inp.setAttribute("aria-invalid", "true");
  }

  async function submit(ev) {
    ev.preventDefault();
    const form = ev.target;
    form.querySelectorAll(".field-error").forEach((e) => { e.textContent = ""; });
    form.querySelectorAll("[aria-invalid]").forEach((e) => e.removeAttribute("aria-invalid"));
    const errBox = document.getElementById("form-error");
    errBox.textContent = "";
    if (!canSend()) return;

    const d = collect(form);
    let bad = null;
    const flag = (id, msg) => { showError(id, msg); bad = bad || id; };
    for (const f of template().fields) {
      const v = d.fields[f.id];
      if (f.required && !v) flag(f.id, t("required"));
      else if (v && f.type === "url" && !/^https?:\/\/\S+\.\S+/.test(v)) flag(f.id, "https://…");
    }
    if (!d.contributor.name) flag("c_name", t("required"));
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.contributor.email)) flag("c_email", t("required"));
    if (d.contributor.credit_mode === "pseudonym" && !d.contributor.credit_name) flag("c_credit_name", t("required"));
    const consent = { terms_version: F.site.terms_version };
    let missingConsent = false;
    for (const c of CONSENTS) {
      consent[c] = form.elements["consent_" + c].checked;
      if (!consent[c]) missingConsent = true;
    }
    let token = "";
    if (F.site.turnstile_sitekey && window.turnstile && turnstileId !== null) token = window.turnstile.getResponse(turnstileId) || "";

    if (bad || missingConsent) {
      errBox.textContent = t("error_fields");
      const target = bad ? document.getElementById("f-" + bad) : form.querySelector("#consent input:not(:checked)");
      if (target) target.focus();
      return;
    }
    if (F.site.turnstile_sitekey && !token) { errBox.textContent = t("error_captcha"); return; }

    const btn = form.querySelector("button[type=submit]");
    btn.disabled = true; btn.textContent = t("sending");
    try {
      const res = await fetch(F.site.worker_url, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          book: book.id, page: page.id, segment: seg, template: tplId, lang,
          fields: d.fields, contributor: d.contributor, consent, turnstile: token, website: d.website,
        }),
      });
      const out = await res.json().catch(() => ({}));
      if (!res.ok || !out.ok) {
        if (out.field) { showError(out.field, out.error || t("required")); errBox.textContent = t("error_fields"); }
        else errBox.textContent = t("error_send");
        throw new Error(out.error || res.status);
      }
      store.del(draftKey());
      done(out.ref);
    } catch (e) {
      btn.disabled = false; btn.textContent = t("send");
      if (window.turnstile && turnstileId !== null) window.turnstile.reset(turnstileId);
    }
  }

  function done(ref) {
    const back = backHref();
    app.replaceChildren(el("div", { class: "notice sent", tabindex: "-1" },
      el("h1", { text: t("sent_title") }),
      el("p", {}, t("sent_body") + " ", el("strong", { text: "#" + ref })),
      el("p", { class: "actions" },
        el("a", { class: "btn", href: back, text: t("sent_back") }),
        el("a", { class: "btn btn-ghost", href: location.href, text: t("another") }))));
    app.firstChild.focus();
  }
})();
