-- Interface text for the contribution form, the terms page and the shelf.
-- {v} is replaced by the terms version.

local function L(en, pt) return { en = en, pt = pt } end

return {
  contribute_to   = L("Contribute to", "Contribuir com"),
  you_are_reading = L("You were reading", "Você estava lendo"),
  segment         = L("Section", "Seção"),
  whole_page      = L("The whole page", "A página inteira"),
  choose_form     = L("What would you like to add?", "O que você quer acrescentar?"),
  required        = L("required", "obrigatório"),
  optional        = L("optional", "opcional"),
  chars_left      = L("characters left", "caracteres restantes"),
  notes_label     = L("Anything else the author should know?", "Algo mais que o autor deva saber?"),

  about_you       = L("About you", "Sobre você"),
  name            = L("Your name", "Seu nome"),
  email           = L("Your email", "Seu e-mail"),
  email_help      = L("Only for review, credit and the notice in section 6 of the terms. Never published.",
                      "Só para revisão, crédito e o aviso da seção 6 do termo. Nunca é publicado."),
  credit_mode     = L("How should you be credited?", "Como você quer ser creditado(a)?"),
  credit_name_opt = L("By my name", "Pelo meu nome"),
  credit_pseudo   = L("By a pseudonym", "Por um pseudônimo"),
  credit_anon     = L("Anonymously", "Anonimamente"),
  credit_name     = L("Pseudonym", "Pseudônimo"),

  consent         = L("Consent", "Consentimento"),
  consent_terms   = L("I have read and accept the Contribution Terms, version {v}.",
                      "Li e aceito o Termo de Contribuição, versão {v}."),
  read_terms      = L("Read the terms", "Ler o termo"),
  consent_original = L("This contribution is my own original work and copies no one else's protected material (section 2).",
                       "Esta contribuição é original, de minha autoria, e não copia material protegido de terceiros (seção 2)."),
  consent_adult   = L("I am 18 or older, or I am sending this with my legal guardian's consent.",
                      "Tenho 18 anos ou mais, ou envio com a autorização do meu responsável legal."),
  consent_future  = L("I understand that if the work is ever published commercially I will receive no payment, and will be credited as a co-author according to the levels in section 7.",
                      "Entendo que, se a obra for publicada comercialmente no futuro, não receberei nenhum valor financeiro e serei creditado(a) como coautor(a) conforme os níveis da seção 7."),
  consent_data    = L("I allow my name and email to be used for review, credit and contact, as described in section 9.",
                      "Autorizo o uso do meu nome e e-mail para revisão, crédito e contato, como descrito na seção 9."),

  send            = L("Send for review", "Enviar para revisão"),
  sending         = L("Sending…", "Enviando…"),
  sent_title      = L("Received. Thank you!", "Recebido. Obrigado!"),
  sent_body       = L("Your contribution is waiting for the author's review. Reference number:",
                      "Sua contribuição está aguardando a revisão do autor. Número de protocolo:"),
  sent_back       = L("Back to the page", "Voltar para a página"),
  another         = L("Send another", "Enviar outra"),
  closed_title    = L("Contributions are not open yet", "As contribuições ainda não estão abertas"),
  closed_body     = L("The form works, but sending is switched off until the author opens contributions. You can still look around.",
                      "O formulário funciona, mas o envio fica desligado até o autor abrir as contribuições. Fique à vontade para explorar."),
  error_fields    = L("Some fields need attention.", "Alguns campos precisam de atenção."),
  error_send      = L("It could not be sent. Your text is still here; try again in a moment.",
                      "Não foi possível enviar. Seu texto continua aqui; tente de novo em instantes."),
  error_captcha   = L("Please complete the anti-spam check.", "Complete a verificação anti-spam."),
  draft_saved     = L("Draft kept on this device", "Rascunho guardado neste aparelho"),
  not_found       = L("This page does not accept contributions, or the link is broken.",
                      "Esta página não aceita contribuições, ou o link está quebrado."),
  language        = L("Language", "Idioma"),
  terms_title     = L("Contribution Terms", "Termo de Contribuição"),
  shelf           = L("Shelf", "Estante"),
}
