// Magic Stack — contribution Worker (Cloudflare Workers).
//
// POST /submit  ← the form on contribute.html
//   1. checks origin, size, honeypot and the Turnstile anti-spam token
//   2. validates the submission against forms.json (the same file the form
//      is rendered from, generated by build.lua)
//   3. opens an issue in the private contributions repository, with the
//      content, the consent record and a Lua draft ready to paste into data/
//
// Settings (wrangler.toml [vars]):  ALLOWED_ORIGINS, FORMS_URL, SITE_URL, GITHUB_REPO
// Secrets (wrangler secret put):    GITHUB_TOKEN, TURNSTILE_SECRET

const MAX_BODY = 64 * 1024;
const FORMS_TTL_MS = 5 * 60 * 1000;
const CONSENTS = ["terms", "original", "adult", "future", "data"];
const CREDIT_MODES = ["name", "pseudonym", "anonymous"];
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const URL_RE = /^https?:\/\/[^\s<>"]+\.[^\s<>"]+$/;

let formsCache = null; // { at, data }

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const origin = request.headers.get("origin") || "";
    const allowed = (env.ALLOWED_ORIGINS || "").split(",").map((s) => s.trim()).filter(Boolean);
    const cors = {
      "access-control-allow-origin": allowed.includes(origin) ? origin : allowed[0] || "null",
      "access-control-allow-methods": "POST, OPTIONS",
      "access-control-allow-headers": "content-type",
      "access-control-max-age": "86400",
      vary: "origin",
    };
    const reply = (status, body) =>
      new Response(JSON.stringify(body), { status, headers: { ...cors, "content-type": "application/json; charset=utf-8" } });

    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
    if (request.method === "GET" && url.pathname === "/") return new Response("Magic Stack contributions: OK", { headers: cors });
    if (url.pathname !== "/submit") return reply(404, { ok: false, error: "not found" });
    if (request.method !== "POST") return reply(405, { ok: false, error: "method not allowed" });
    if (!allowed.includes(origin)) return reply(403, { ok: false, error: "origin not allowed" });

    // ---- body ----
    const len = Number(request.headers.get("content-length") || 0);
    if (len > MAX_BODY) return reply(413, { ok: false, error: "too large" });
    let raw;
    try { raw = await request.text(); } catch { return reply(400, { ok: false, error: "unreadable body" }); }
    if (raw.length > MAX_BODY) return reply(413, { ok: false, error: "too large" });
    let sub;
    try { sub = JSON.parse(raw); } catch { return reply(400, { ok: false, error: "invalid JSON" }); }
    if (!sub || typeof sub !== "object") return reply(400, { ok: false, error: "invalid submission" });

    // honeypot: pretend success so bots learn nothing
    if (sub.website) return reply(200, { ok: true, ref: "0" });

    // ---- anti-spam ----
    if (!env.TURNSTILE_SECRET) return reply(503, { ok: false, error: "contributions are not configured" });
    const human = await verifyTurnstile(env.TURNSTILE_SECRET, sub.turnstile, request.headers.get("cf-connecting-ip"));
    if (!human) return reply(403, { ok: false, error: "anti-spam check failed" });

    // ---- validate against forms.json ----
    let forms;
    try { forms = await loadForms(env.FORMS_URL); } catch (e) { return reply(502, { ok: false, error: "forms unavailable" }); }
    const v = validate(sub, forms);
    if (v.error) return reply(400, { ok: false, error: v.error, field: v.field });

    // ---- open the issue ----
    if (!env.GITHUB_TOKEN || !env.GITHUB_REPO) return reply(503, { ok: false, error: "contributions are not configured" });
    const issue = buildIssue(v, env.SITE_URL || "", new Date());
    const gh = await fetch(`https://api.github.com/repos/${env.GITHUB_REPO}/issues`, {
      method: "POST",
      headers: {
        authorization: `Bearer ${env.GITHUB_TOKEN}`,
        accept: "application/vnd.github+json",
        "x-github-api-version": "2022-11-28",
        "user-agent": "magic-stack-contrib",
        "content-type": "application/json",
      },
      body: JSON.stringify(issue),
    });
    if (!gh.ok) {
      console.error("github", gh.status, await gh.text().catch(() => ""));
      return reply(502, { ok: false, error: "could not file the contribution" });
    }
    const created = await gh.json();
    return reply(200, { ok: true, ref: String(created.number) });
  },
};

// ---------------------------------------------------------------------------
async function verifyTurnstile(secret, token, ip) {
  if (!token || typeof token !== "string" || token.length > 2048) return false;
  const form = new FormData();
  form.append("secret", secret);
  form.append("response", token);
  if (ip) form.append("remoteip", ip);
  try {
    const r = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", { method: "POST", body: form });
    const out = await r.json();
    return out.success === true;
  } catch {
    return false;
  }
}

async function loadForms(formsUrl) {
  if (formsCache && Date.now() - formsCache.at < FORMS_TTL_MS) return formsCache.data;
  const r = await fetch(formsUrl, { cf: { cacheTtl: 300 } });
  if (!r.ok) throw new Error("forms " + r.status);
  const data = await r.json();
  formsCache = { at: Date.now(), data };
  return data;
}

export function _resetCache() { formsCache = null; }

// ---------------------------------------------------------------------------
const str = (x) => (typeof x === "string" ? x.replace(/\r\n?/g, "\n").trim() : "");

export function validate(sub, forms) {
  const book = forms.books[sub.book];
  if (!book || !book.open) return { error: "unknown or closed book", field: null };
  const page = book.pages[sub.page];
  if (!page) return { error: "unknown page", field: null };
  if (!page.templates.includes(sub.template)) return { error: "this page does not take that form", field: null };
  const tpl = (book.templates && book.templates[sub.template]) || forms.templates[sub.template];
  if (!tpl) return { error: "unknown form", field: null };
  // segments are listed per language (each edition has its own anchors)
  const allSegs = Array.isArray(page.segments) ? page.segments : [].concat(...Object.values(page.segments || {}));
  const segment = sub.segment ? allSegs.find((s) => s.id === sub.segment) : null;
  if (sub.segment && !segment) return { error: "unknown section", field: null };
  const lang = forms.site.langs.includes(sub.lang) ? sub.lang : forms.site.default_lang;

  const fields = {};
  const given = sub.fields && typeof sub.fields === "object" ? sub.fields : {};
  for (const f of tpl.fields) {
    const val = str(given[f.id]);
    if (f.required && !val) return { error: "required", field: f.id };
    if (!val) { fields[f.id] = ""; continue; }
    if (f.max && f.type !== "number" && val.length > f.max) return { error: `max ${f.max} characters`, field: f.id };
    if (f.type === "select" && !f.options.some((o) => o.value === val)) return { error: "invalid option", field: f.id };
    if (f.type === "url" && !URL_RE.test(val)) return { error: "invalid link", field: f.id };
    if (f.type === "number") {
      const n = Number(val);
      if (!Number.isFinite(n) || (f.min != null && n < f.min) || (f.max != null && n > f.max)) return { error: "invalid number", field: f.id };
    }
    fields[f.id] = val;
  }
  if (tpl.id === "timeline-event" && fields.kind === "history" && !fields.source) return { error: "real events need a source", field: "source" };

  const c = sub.contributor && typeof sub.contributor === "object" ? sub.contributor : {};
  const contributor = {
    name: str(c.name), email: str(c.email).toLowerCase(),
    credit_mode: CREDIT_MODES.includes(c.credit_mode) ? c.credit_mode : "name",
    credit_name: str(c.credit_name),
  };
  if (!contributor.name || contributor.name.length > 120) return { error: "required", field: "c_name" };
  if (!EMAIL_RE.test(contributor.email) || contributor.email.length > 200) return { error: "invalid email", field: "c_email" };
  if (contributor.credit_mode === "pseudonym" && (!contributor.credit_name || contributor.credit_name.length > 80))
    return { error: "required", field: "c_credit_name" };

  const consent = sub.consent && typeof sub.consent === "object" ? sub.consent : {};
  if (consent.terms_version !== forms.site.terms_version) return { error: "terms version changed, reload the page", field: null };
  for (const k of CONSENTS) if (consent[k] !== true) return { error: "all consent boxes are required", field: null };

  return { book: { id: sub.book, ...book }, page: { id: sub.page, ...page }, segment, tpl, lang, fields, contributor,
           consent: Object.fromEntries([["terms_version", consent.terms_version], ...CONSENTS.map((k) => [k, true])]) };
}

// ---------------------------------------------------------------------------
// Markdown issue
// ---------------------------------------------------------------------------
const tx = (o, lang) => (typeof o === "string" ? o : o ? o[lang] || o.en : "");
// user text: neutralise @mentions, #refs and raw HTML in the issue
const safe = (s) => s.replace(/@/g, "@​").replace(/#(\d)/g, "#​$1").replace(/</g, "&lt;");
const quote = (s) => safe(s).split("\n").map((l) => "> " + l).join("\n");

function creditLine(c) {
  if (c.credit_mode === "anonymous") return "Anônimo (não publicar o nome)";
  if (c.credit_mode === "pseudonym") return `Pseudônimo: **${safe(c.credit_name)}**`;
  return `Nome: **${safe(c.name)}**`;
}

function headline(v) {
  const f = v.fields;
  return f.name || f.title || f.heading || (f.year ? `${f.year}` : "") || v.tpl.id;
}

export function buildIssue(v, siteUrl, now) {
  const { book, page, segment, tpl, fields, contributor, consent, lang } = v;
  const pageUrl = `${siteUrl}${book.id}/${lang}/${page.id}.html${segment ? "#" + segment.id : ""}`;
  const bookTitle = tx(book.title, "pt"), pageTitle = tx(page.title, "pt");
  const title = `[${bookTitle}] ${pageTitle}${segment ? " › " + segment.title : ""} — ${tx(tpl.title, "pt")}: ${headline(v)}`.slice(0, 250);

  const content = tpl.fields
    .filter((f) => fields[f.id])
    .map((f) => {
      let val = fields[f.id];
      if (f.type === "select") val = tx((f.options.find((o) => o.value === val) || {}).label, "pt") || val;
      return `### ${tx(f.label, "pt")}\n\n${quote(val)}`;
    })
    .join("\n\n");

  const record = {
    book: book.id, page: page.id, segment: segment ? segment.id : "", template: tpl.id, lang,
    contributor, consent: { ...consent, accepted_at: now.toISOString() }, fields,
  };

  const body = [
    `## ${tx(tpl.title, "pt")}`,
    "",
    "| | |",
    "|---|---|",
    `| Livro | ${bookTitle} |`,
    `| Página | [${pageTitle}](${pageUrl}) |`,
    `| Seção | ${segment ? segment.title : "página inteira"} |`,
    `| Formulário | \`${tpl.id}\` |`,
    `| Idioma do envio | ${lang} |`,
    `| Recebido em | ${now.toISOString()} |`,
    "",
    "## Contribuidor(a)",
    "",
    `- Nome: ${safe(contributor.name)}`,
    `- E-mail: ${contributor.email}`,
    `- Crédito: ${creditLine(contributor)}`,
    "",
    "## Conteúdo",
    "",
    content,
    "",
    "## Rascunho em Lua",
    "",
    "Ponto de partida para colar em `data/` depois de editar. O build vai validar links, fontes e fichas.",
    "",
    "```lua",
    luaDraft(v, now),
    "```",
    "",
    "## Revisão",
    "",
    "- [ ] Ler e editar o texto",
    "- [ ] Definir o nível de crédito: `crédito:1-contribuidor` · `crédito:2-colaborador` · `crédito:3-coautor`",
    `- [ ] Incorporar em \`books/${book.id}/data/\` e rodar \`lua build.lua\``,
    "- [ ] Avisar o(a) contribuidor(a) por e-mail sobre a decisão e o nível de crédito",
    "",
    "## Consentimento",
    "",
    `Termo de Contribuição **v${consent.terms_version}**, aceito em ${now.toISOString()}:`,
    CONSENTS.map((k) => `\`${k}\` ✔`).join(" · "),
    "",
    `<!-- magic-stack-submission ${JSON.stringify(record).replace(/--/g, "\\u002d\\u002d")} -->`,
  ].join("\n");

  return {
    title,
    body,
    labels: ["contribuição", "aguardando-revisão", `livro:${book.id}`, `tipo:${tpl.id}`],
  };
}

// ---------------------------------------------------------------------------
// Lua draft
// ---------------------------------------------------------------------------
export function slug(s) {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase()
    .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "untitled";
}

function luaQ(s) {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n") + '"';
}

function luaLong(s) {
  let eq = "==";
  while (s.includes("]" + eq + "]")) eq += "=";
  return `[${eq}[\n${s}\n]${eq}]`;
}

const comment = (s) => s.split("\n").map((l) => "-- " + l).join("\n");

function creditComment(v, now) {
  const c = v.contributor;
  const who = c.credit_mode === "anonymous" ? "anonymous" : c.credit_mode === "pseudonym" ? c.credit_name : c.name;
  return `-- contributed by ${who} (${now.toISOString().slice(0, 10)}) · credit level: TODO`;
}

function bodyBlocks(v, ids) {
  const lang = v.book.lang || "en";
  return ids
    .filter((id) => v.fields[id])
    .map((id) => {
      const f = v.tpl.fields.find((x) => x.id === id);
      return `## ${tx(f.label, lang)}\n${v.fields[id]}`;
    })
    .join("\n\n");
}

function parseCharacteristics(s) {
  const ALIASES = { FOR: "STR", TAM: "SIZ", DES: "DEX", APA: "APP", POD: "POW" };
  const out = {};
  for (const m of s.matchAll(/\b([A-Za-z]{3})\b\s*[:=]?\s*(\d{1,2})\b/g)) {
    const k = ALIASES[m[1].toUpperCase()] || m[1].toUpperCase();
    if (["STR", "CON", "SIZ", "DEX", "APP", "INT", "POW", "EDU"].includes(k)) out[k] = Number(m[2]);
  }
  return out;
}

function parseSkills(s) {
  const out = [];
  for (const line of s.split(/[\n;,]+/)) {
    const m = line.trim().match(/^(.+?)\s*[:\-–]?\s*(\d{1,2})\s*%?$/);
    if (m) out.push([m[1].trim(), Number(m[2])]);
  }
  return out;
}

export function luaDraft(v, now) {
  const { tpl, fields: f, page, segment } = v;
  const d = tpl.draft;
  const credit = creditComment(v, now);
  const lines = [];

  if (d.shape === "page") {
    const kind = d.kind ? f[d.kind] || "fiction" : "fiction";
    lines.push(`-- new entry for data/pages.lua (section "${page.section}")`, credit, "{");
    lines.push(`  id = ${luaQ(slug(f[d.title]))}, section = ${luaQ(page.section)}, kind = ${luaQ(kind)},`);
    lines.push(`  title = ${luaQ(f[d.title])},`);
    lines.push(`  summary = ${luaQ(f[d.summary] || "")},`);
    lines.push(`  body = ${luaLong(bodyBlocks(v, d.body))},`);
    lines.push("},");
    if (f.source) lines.push(`-- source given: ${f.source} → add it to data/sources.lua and cite it with {{id}}`);
  } else if (d.shape === "segment") {
    lines.push(`-- append to the body of "${page.id}" in data/pages.lua` + (segment ? `, near "## ${segment.title}"` : ""), credit);
    lines.push(`## ${f[d.heading]}`);
    lines.push(d.body.filter((id) => f[id]).map((id) => f[id]).join("\n\n"));
    if (f.source) lines.push(`-- source given: ${f.source} → add it to data/sources.lua and cite it with {{id}}`);
  } else if (d.shape === "investigator") {
    const ch = parseCharacteristics(f[d.characteristics] || "");
    const sk = parseSkills(f[d.skills] || "");
    lines.push("-- new entry for data/investigators.lua", credit, "{");
    lines.push(`  id = ${luaQ(slug(f[d.name]))},`);
    lines.push(`  name = ${luaQ(f[d.name])},`);
    lines.push(`  role = ${luaQ(f[d.role])},`);
    lines.push(`  occupation = ${luaQ(f[d.occupation])},`);
    lines.push(`  quote = ${luaQ(f[d.quote])},`);
    lines.push(`  motivation = ${luaQ(f[d.motivation])},`);
    lines.push(`  hook = ${luaQ(f[d.hook])},`);
    lines.push("  links = { }, -- TODO: page ids this investigator touches");
    const keys = ["STR", "CON", "SIZ", "DEX", "APP", "INT", "POW", "EDU"];
    if (keys.every((k) => ch[k] != null)) {
      lines.push(`  characteristics = { ${keys.map((k) => `${k} = ${ch[k]}`).join(", ")} },`);
      lines.push(`  declared = { HP = ${Math.floor((ch.CON + ch.SIZ) / 10)}, SAN = ${ch.POW} },`);
    } else {
      lines.push("  characteristics = { }, -- TODO: incomplete, as sent:");
      if (f[d.characteristics]) lines.push(comment(f[d.characteristics]).replace(/^/gm, "  "));
    }
    lines.push("  skills = {");
    for (const [name, val] of sk) lines.push(`    { ${luaQ(name)}, ${val} },`);
    lines.push("  },");
    lines.push(`  gear = ${luaQ(f[d.gear] || "")},`);
    lines.push("},");
  } else if (d.shape === "timeline") {
    lines.push("-- new entry for data/timeline.lua (keep the list in date order)", credit);
    const kind = f[d.kind] === "history" ? "history" : "fiction";
    const src = kind === "history" ? ` source = "TODO", -- ${f[d.source]}` : "";
    lines.push(`{ year = ${luaQ(f[d.year])}, kind = ${luaQ(kind)},${src}`);
    lines.push(`  text = ${luaQ(f[d.text])} },`);
  } else if (d.shape === "scene") {
    lines.push("-- new node for data/flow.lua; also add an exit to it from the scenes it comes from", credit);
    lines.push("{ id = " + luaQ(slug(f[d.title])) + ", title = " + luaQ(f[d.title]) + `, page = ${luaQ(page.id === "scenario-flow" ? "TODO" : page.id)},`);
    lines.push(`  text = ${luaQ(f[d.text])},`);
    lines.push("  next = {");
    lines.push(comment(`exits, as sent:\n${f[d.exits]}`).replace(/^/gm, "    "));
    lines.push("  } },");
    lines.push(comment(`comes from, as sent:\n${f[d.from]}`));
    for (const id of d.body || []) if (f[id]) lines.push(comment(`${id}: ${f[id]}`));
  } else if (d.shape === "source") {
    lines.push("-- new entry for data/sources.lua (the build fails until a page cites it)", credit, "{");
    lines.push(`  id = ${luaQ(slug(f[d.title]))},`);
    lines.push(`  title = ${luaQ(f[d.title])},`);
    lines.push(`  publisher = ${luaQ(f[d.publisher])},`);
    lines.push(`  url = ${luaQ(f[d.url])},`);
    lines.push(`  note = ${luaQ(f[d.note])},`);
    lines.push("},");
  }
  if (f.notes) lines.push("", comment(`note from the contributor: ${f.notes}`));
  return lines.join("\n").replace(/```/g, "ˋˋˋ");
}
