-- tools/cover.lua — writes cover.html, the book's red cover on the Magic
-- Stack table (150×200 px): the title, a small pixel map of the board, a
-- row of army pieces and the War dice. Run it from the book folder after
-- changing the map or the territories:
--
--   lua tools/cover.lua > cover.html
--
-- {{TITLE}}, {{SYSTEM}} and {{AUTHOR}} are filled in by the root build.lua
-- in each language. The shelf page loads Silkscreen and Pirata One.

local map = dofile("tools/map.lua")
local grid = dofile("data/worldgrid.lua")
local t = dofile("data/territories.lua")

local out = {}
local function add(s) out[#out + 1] = s end

-- the board: 3 grid cells per dot, 2 px per dot, cropped to 78N–40S
local svg = {}
local K, PX = 3, 2
local rows = 60
local w, h = (grid.cols // K) * PX, (rows // K) * PX
svg[#svg + 1] = string.format('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d" shape-rendering="crispEdges" style="display:block">', w, h, w, h)
svg[#svg + 1] = string.format('<rect width="%d" height="%d" fill="%s"/>', w, h, t.sea.water)
for y = 0, h - 1, 4 do
  for x = (y % 8 == 0) and 0 or 2, w - 1, 4 do svg[#svg + 1] = string.format('<rect x="%d" y="%d" width="1" height="1" fill="%s"/>', x, y, t.sea.water2) end
end
svg[#svg + 1] = map.mini(grid, t, { k = K, px = PX, x = 0, y = 0, r1 = rows })
-- the skull over the flooded triangle
do
  local c, r = map.cell_at(grid, 42.5, 12)
  map.sprite(map.SKULL, { X = "#0b0b14", W = "#f3e6d0" }, (c // K) * PX - 3, (r // K) * PX - 3, 1, svg)
end
svg[#svg + 1] = "</svg>"

-- army pieces and dice, below the map
local pieces = {}
pieces[#pieces + 1] = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 12" width="120" height="12" shape-rendering="crispEdges" style="display:block">'
local x = 0
for i, e in ipairs({ t.estemps[1], t.estemps[2], t.estemps[3], t.estemps[4], t.sea }) do
  map.sprite(map.PIECE, { X = "#0b0b14", L = e.light, C = e.color, D = e.dark }, x, 2, 1, pieces)
  x = x + 10
end
map.sprite(map.DIE, { X = "#0b0b14", C = "#c8322e", P = "#f3e6d0" }, 64, 2, 1, pieces)
map.sprite(map.DIE, { X = "#0b0b14", C = "#c8322e", P = "#f3e6d0" }, 73, 2, 1, pieces)
map.sprite(map.DIE, { X = "#0b0b14", C = "#e0b23a", P = "#0b0b14" }, 86, 2, 1, pieces)
map.sprite(map.DIE, { X = "#0b0b14", C = "#e0b23a", P = "#0b0b14" }, 95, 2, 1, pieces)
map.sprite(map.DIE, { X = "#0b0b14", C = "#e0b23a", P = "#0b0b14" }, 104, 2, 1, pieces)
pieces[#pieces + 1] = "</svg>"

add("<!-- Cover of O Amanhã Corporativo on the Magic Stack table (150×200 px).")
add("     Generated by tools/cover.lua from data/worldgrid.lua and data/territories.lua; do not edit by hand.")
add("     {{TITLE}}, {{SYSTEM}} and {{AUTHOR}} are filled by the build, in each language. -->")
add('<div style="position:absolute; inset:0; overflow:hidden; background:#8e1b1b; background-image:repeating-linear-gradient(0deg, rgb(0 0 0 / .07) 0 1px, transparent 1px 4px);">')
add('  <span style="position:absolute; left:0; right:0; top:0; height:6px; background:repeating-linear-gradient(90deg, #e0b23a 0 6px, #8e1b1b 6px 12px);"></span>')
add('  <div style="position:absolute; left:10px; right:10px; top:14px; display:flex; flex-direction:column; gap:3px;">')
add("    <div style=\"font-family:'Silkscreen', monospace; font-weight:700; font-size:15px; line-height:1.02; color:#f3e6d0; text-transform:uppercase; text-shadow:2px 2px 0 #0b0b14;\">{{TITLE}}</div>")
add("    <div style=\"font-family:'Silkscreen', monospace; font-size:7px; color:#e0b23a; letter-spacing:.06em;\">{{SYSTEM}} · 2126</div>")
add("  </div>")
add(string.format('  <div style="position:absolute; left:%dpx; top:76px; box-shadow:0 0 0 2px #0b0b14, 0 0 0 4px #e0b23a, 0 0 0 6px #0b0b14;">%s</div>', (150 - w) // 2, table.concat(svg)))
add(string.format('  <div style="position:absolute; left:15px; top:%dpx;">%s</div>', 76 + h + 10, table.concat(pieces)))
add("  <div style=\"position:absolute; left:10px; right:10px; bottom:9px; font-family:'Silkscreen', monospace; font-size:7px; line-height:1.3; color:#f3e6d0;\">{{AUTHOR}}</div>")
add('  <span style="position:absolute; inset:0; box-shadow:inset 0 0 0 2px #0b0b14, inset 0 0 0 4px #b5302a;"></span>')
add("</div>")
print(table.concat(out, "\n"))
