#!/usr/bin/env python3
"""Generate data/worldgrid.lua: the world as a grid of pixels, each pixel
holding the letter of the corporate state (ESTEMP) that owns it in 2126.

The build never runs this script; it only reads the Lua file it writes.
Run it again only to change the grid or which country went to which ESTEMP.

    python3 tools/worldgrid.py countries.geo.json > data/worldgrid.lua

countries.geo.json: https://github.com/johan/world.geo.json (public domain,
derived from Natural Earth). No third-party Python packages are needed.
"""
import json
import sys

# grid: 2 degrees per pixel, 180 columns, latitudes 78N to 56S
STEP = 2.0
LON0, LAT0 = -180.0, 78.0
COLS, ROWS = 180, 67
SUB = 4          # 4x4 samples per pixel
MIN_HITS = 4     # a pixel is land if at least 4 of 16 samples are land

# Which ESTEMP owns each country (ISO 3166 alpha-3). Unlisted = O (Americas
# are checked below) or error.
OWNER = {}
def own(code, *isos):
    for i in isos:
        OWNER[i] = code

# O OmniTerra — the Americas
own("O", "USA", "CAN", "MEX", "GTM", "BLZ", "HND", "SLV", "NIC", "CRI", "PAN", "CUB", "JAM", "HTI",
    "DOM", "PRI", "BHS", "TTO", "COL", "VEN", "GUY", "SUR", "GUF", "ECU", "PER", "BOL", "BRA",
    "PRY", "URY", "ARG", "CHL", "FLK", "GRL", "BMU")
# K Kuro-Tech — East and Southeast Asia, Oceania
own("K", "CHN", "JPN", "KOR", "PRK", "TWN", "MNG", "VNM", "LAO", "KHM", "THA", "MMR", "MYS", "BRN",
    "IDN", "PHL", "TLS", "PNG", "AUS", "NZL", "NCL", "SLB", "VUT", "FJI")
# A Aegis-Med — Europe and Mediterranean Africa
own("A", "PRT", "ESP", "FRA", "GBR", "IRL", "ISL", "NOR", "SWE", "FIN", "DNK", "DEU", "NLD", "BEL",
    "LUX", "CHE", "AUT", "ITA", "MLT", "SVN", "HRV", "BIH", "SRB", "CS-KM", "MNE", "ALB", "MKD",
    "GRC", "BGR", "ROU", "MDA", "HUN", "SVK", "CZE", "POL", "LTU", "LVA", "EST", "BLR", "UKR", "CYP",
    "MAR", "DZA", "TUN", "LBY", "EGY")
# P Petro-Vanguard — Middle East and Central Asia
own("P", "TUR", "SYR", "LBN", "ISR", "PSE", "JOR", "IRQ", "KWT", "SAU", "YEM", "OMN", "ARE", "QAT",
    "IRN", "AFG", "TKM", "UZB", "KAZ", "KGZ", "TJK", "GEO", "ARM", "AZE")
# M Monsoon Workforce Solutions — South Asia
own("M", "IND", "PAK", "BGD", "NPL", "BTN", "LKA")
# V Severa Combine — Russia and the Arctic
own("V", "RUS")
# R Great Rift Holdings — East, Central and Southern Africa
own("R", "ETH", "ERI", "SOM", "KEN", "UGA", "TZA", "RWA", "BDI", "COD", "SSD", "ZMB", "MWI", "MOZ",
    "ZWE", "AGO", "NAM", "BWA", "ZAF", "LSO", "SWZ", "MDG", "DJI")
# S Sahel Solar Trust — West Africa and the Sahara
own("S", "MRT", "ESH", "MLI", "NER", "TCD", "SDN", "SEN", "GMB", "GIN", "GNB", "SLE", "LBR", "CIV",
    "GHA", "TGO", "BEN", "BFA", "NGA", "CMR", "GAB", "COG", "GNQ", "CAF")
SKIP = {"ATA", "ATF"}
BY_NAME = {"Northern Cyprus": "A", "Somaliland": "R"}


def rings_of(geom):
    if geom["type"] == "Polygon":
        return [geom["coordinates"]]
    return geom["coordinates"]


def inside(x, y, ring):
    c = False
    n = len(ring)
    j = n - 1
    for i in range(n):
        xi, yi = ring[i][0], ring[i][1]
        xj, yj = ring[j][0], ring[j][1]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi) + xi:
            c = not c
        j = i
    return c


def main(path):
    feats = json.load(open(path))["features"]
    polys = []
    for f in feats:
        iso, name = f["id"], f["properties"]["name"]
        if iso in SKIP:
            continue
        code = BY_NAME.get(name) or OWNER.get(iso)
        if not code:
            raise SystemExit("no owner for %s %s" % (iso, name))
        for poly in rings_of(f["geometry"]):
            outer = poly[0]
            xs = [p[0] for p in outer]
            ys = [p[1] for p in outer]
            polys.append((code, (min(xs), min(ys), max(xs), max(ys)), poly))

    rows = []
    for r in range(ROWS):
        line = []
        for c in range(COLS):
            hits = {}
            for sy in range(SUB):
                for sx in range(SUB):
                    x = LON0 + (c + (sx + .5) / SUB) * STEP
                    y = LAT0 - (r + (sy + .5) / SUB) * STEP
                    for code, (x0, y0, x1, y1), poly in polys:
                        if x0 <= x <= x1 and y0 <= y <= y1 and inside(x, y, poly[0]) \
                                and not any(inside(x, y, h) for h in poly[1:]):
                            hits[code] = hits.get(code, 0) + 1
                            break
            total = sum(hits.values())
            line.append(max(hits, key=hits.get) if total >= MIN_HITS else ".")
        rows.append("".join(line))

    print("-- Generated by tools/worldgrid.py from countries.geo.json (Natural Earth, public domain).")
    print("-- One letter per pixel, 2 degrees each: columns from 180W, rows from 78N to 56S.")
    print("-- Letters are ESTEMPs (see data/territories.lua); '.' is sea, owned by Thalassa Corp.")
    print("return {")
    print("  step = %g, lon0 = %g, lat0 = %g, cols = %d," % (STEP, LON0, LAT0, COLS))
    print("  rows = {")
    for line in rows:
        print('    "%s",' % line)
    print("  },")
    print("}")


if __name__ == "__main__":
    main(sys.argv[1])
