-- Interface text for book pages (everything that is not the story itself),
-- in every language the shelf supports. Books' own build.lua files load this.

return {
  en = {
    html_lang = "en",
    sections = {
      ["The Scenario"] = "The Scenario", ["Places"] = "Places", ["The Mythos"] = "The Mythos",
      ["Factions"] = "Factions", ["Investigators"] = "Investigators", ["Endings"] = "Endings", ["Reference"] = "Reference",
    },
    kinds = { history = "History", fiction = "Fiction", mixed = "History + Fiction" },
    skip = "Skip to content",
    contents = "Contents",
    nav_label = "Book contents",
    shelf = "← Shelf",
    shelf_title = "Back to the Magic Stack shelf",
    language = "Language",
    footer = "<em>%s</em> — an original Call of Cthulhu 7e scenario by %s. Built from Lua data with <code>build.lua</code>.",
    on_this_page = "On this page",
    refs_here = "References on this page",
    referenced_from = "Referenced from",
    previous = "Previous", next = "Next",
    seg_link = "+ contribute",
    seg_title = "Contribute to “%s”",
    add_title = "Add to this page",
    add_text = "Have a character, a scene, a clue or a correction that belongs here? Send it in. Every contribution is reviewed by the author, and accepted ones are credited in the book.",
    add_btn = "Contribute to “%s”",
    timeline_lede = 'Documented events carry a citation. Scenario events are marked <span class="tag tag-fiction">Fiction</span>.',
    flow_lede = "%d scenes, %d endings. Every scene is reachable from the arrival, and every path leads to an ending; the build script checks both.",
    flow_aria = "Scenario flow diagram",
    flow_caption = "Each box is a scene; click one to jump to it. Hover an arrow to see what opens that path.",
    read_more = "Read more:",
    contact_head = { "Contact", "Effect" },
    sources_lede = "Real-world references behind the history in this book. External links open in a new tab.",
    inv = {
      motivation = "Motivation", hook = "Personal hook", characteristics = "Characteristics",
      char_hint = "Regular value, then Hard (½) / Extreme (⅕).",
      derived_hint = "Derived values are computed by <code>build.lua</code> from the CoC 7e rules.",
      skills = "Key skills", skills_head = { "Skill", "Regular", "Hard", "Extreme" },
      gear = "Equipment (1974)", threads = "Threads to pull",
      chars = { STR = "STR", CON = "CON", SIZ = "SIZ", DEX = "DEX", APP = "APP", INT = "INT", POW = "POW", EDU = "EDU" },
      derived = { "Hit Points", "Sanity", "Magic Points", "Move", "Damage Bonus", "Build" },
      none = "None",
    },
    book = {
      chapter = "Chapter %s", appendix = "Appendices", in_chapter = "In this chapter",
      boxes = { read = "Read aloud", keeper = "Keeper note", history = "Historical note" },
      exits = "Where this scene leads", see_also = "See also",
      contribute_article = "+ Contribute to this article",
      refs_chapter = "Sources cited in this chapter",
      handout = "Handout %d", found_in = "Found in",
      npc = { chars = "Characteristics", sanity = "Sanity", contact = "Contact", attacks = "Attacks",
              attacks_hint = "One attack per round.", dodge = "Dodge", skills = "Skills", armor = "Armour",
              spells = "Spells", notes = "Notes",
              derived = { HP = "HP", MP = "MP", Move = "Move", DB = "DB", Build = "Build" } },
      glance = { title = "At a glance", rows = {
        { "System", "Call of Cthulhu 7th Edition" }, { "Players", "3 investigators (pre-generated included)" },
        { "Length", "2–3 sessions of about 4 hours" }, { "Era", "May–July 1974, Paranapiacaba, Brazil" },
        { "Tone", "Slow-burn investigative horror, rooted in real history" } } },
      start = "Start reading", play = "Go to the adventure", contents = "Contents",
      scenes = "The scenes",
    },
    cover = {
      open = "Open the grimoire", flow = "See the scenario flow",
      legend = '<span class="tag tag-history">History</span> documented and cited · <span class="tag tag-fiction">Fiction</span> invented for play · <span class="tag tag-mixed">History + Fiction</span> fiction built on fact',
      title_suffix = " — a Call of Cthulhu scenario",
    },
  },

  pt = {
    html_lang = "pt-BR",
    sections = {
      ["The Scenario"] = "O Cenário", ["Places"] = "Locais", ["The Mythos"] = "O Mythos",
      ["Factions"] = "Facções", ["Investigators"] = "Investigadores", ["Endings"] = "Finais", ["Reference"] = "Referência",
    },
    kinds = { history = "História", fiction = "Ficção", mixed = "História + Ficção" },
    skip = "Pular para o conteúdo",
    contents = "Sumário",
    nav_label = "Sumário do livro",
    shelf = "← Estante",
    shelf_title = "Voltar à estante do Magic Stack",
    language = "Idioma",
    footer = "<em>%s</em> — um cenário original de Call of Cthulhu 7e por %s. Gerado a partir de dados em Lua com <code>build.lua</code>.",
    on_this_page = "Nesta página",
    refs_here = "Referências nesta página",
    referenced_from = "Citada em",
    previous = "Anterior", next = "Próxima",
    seg_link = "+ contribuir",
    seg_title = "Contribuir com “%s”",
    add_title = "Acrescente a esta página",
    add_text = "Tem um personagem, uma cena, uma pista ou uma correção que pertence a este lugar? Envie. Toda contribuição é revisada pelo autor, e as aceitas recebem crédito no livro.",
    add_btn = "Contribuir com “%s”",
    timeline_lede = 'Eventos documentados trazem uma citação. Eventos do cenário estão marcados como <span class="tag tag-fiction">Ficção</span>.',
    flow_lede = "%d cenas, %d finais. Toda cena pode ser alcançada a partir da chegada, e todo caminho leva a um final; o script de build confere as duas coisas.",
    flow_aria = "Diagrama do fluxo do cenário",
    flow_caption = "Cada caixa é uma cena; clique para ir até ela. Passe o mouse numa seta para ver o que abre aquele caminho.",
    read_more = "Leia mais:",
    contact_head = { "Contato", "Efeito" },
    sources_lede = "Referências do mundo real por trás da história deste livro. Os links externos abrem numa nova aba.",
    inv = {
      motivation = "Motivação", hook = "Gancho pessoal", characteristics = "Características",
      char_hint = "Valor normal, depois Difícil (½) / Extremo (⅕).",
      derived_hint = "Os valores derivados são calculados pelo <code>build.lua</code> a partir das regras de CoC 7e.",
      skills = "Perícias principais", skills_head = { "Perícia", "Normal", "Difícil", "Extremo" },
      gear = "Equipamento (1974)", threads = "Fios para puxar",
      chars = { STR = "FOR", CON = "CON", SIZ = "TAM", DEX = "DES", APP = "APA", INT = "INT", POW = "POD", EDU = "EDU" },
      derived = { "Pontos de Vida", "Sanidade", "Pontos de Magia", "Movimento", "Bônus de Dano", "Corpo" },
      none = "Nenhum",
    },
    book = {
      chapter = "Capítulo %s", appendix = "Apêndices", in_chapter = "Neste capítulo",
      boxes = { read = "Leia em voz alta", keeper = "Nota do Guardião", history = "Nota histórica" },
      exits = "Para onde a cena leva", see_also = "Veja também",
      contribute_article = "+ Contribuir com este artigo",
      refs_chapter = "Fontes citadas neste capítulo",
      handout = "Handout %d", found_in = "Encontrado em",
      npc = { chars = "Características", sanity = "Sanidade", contact = "Contato", attacks = "Ataques",
              attacks_hint = "Um ataque por rodada.", dodge = "Esquivar", skills = "Perícias", armor = "Armadura",
              spells = "Magias", notes = "Notas",
              derived = { HP = "PV", MP = "PM", Move = "Mov", DB = "BD", Build = "Corpo" } },
      glance = { title = "Num relance", rows = {
        { "Sistema", "Call of Cthulhu 7ª Edição" }, { "Jogadores", "3 investigadores (fichas prontas incluídas)" },
        { "Duração", "2–3 sessões de umas 4 horas" }, { "Época", "Maio–julho de 1974, Paranapiacaba, SP" },
        { "Tom", "Horror investigativo de tensão lenta, ancorado em história real" } } },
      start = "Começar a ler", play = "Ir para a aventura", contents = "Sumário",
      scenes = "As cenas",
    },
    cover = {
      open = "Abrir o grimório", flow = "Ver o fluxo do cenário",
      legend = '<span class="tag tag-history">História</span> documentada e citada · <span class="tag tag-fiction">Ficção</span> inventada para o jogo · <span class="tag tag-mixed">História + Ficção</span> ficção construída sobre fatos',
      title_suffix = " — um cenário de Call of Cthulhu",
    },
  },
}
