-- Book card for the Magic Stack shelf, plus which contribution forms each
-- part of the book offers. Shared form templates live in
-- contribute/templates.lua; this book adds its own in contrib.lua.

return {
  id       = "o-amanha-corporativo",
  title    = "O Amanhã Corporativo",
  subtitle = "Um cenário de Cyberpunk RED · 2126",
  system   = "Cyberpunk RED",
  genre    = "Distopia corporativa",
  author   = "Murillo França M. da Silva",
  lang     = "pt",           -- the story is written in Portuguese (data/); English lives in data/en/
  status   = "in-progress",  -- the world is complete; the opening adventure stops at two open scenes
  blurb    = "Em 2126, o mundo não acabou: foi comprado à prestação. Corporações viraram países, os governos viraram restos, e uma colher virou símbolo de terrorismo.",
  period   = "2126",
  place    = "O mundo inteiro · Brasília",
  kicker   = "Um cenário de Cyberpunk RED pé no chão · O mundo em 2126 · Começo de aventura em Brasília",
  cover_title = "O Amanhã<br>Corporativo",
  banner_alt = "Mapa-múndi em pixel art sobre um tabuleiro vermelho: cada continente pintado na cor de uma corporação, com pilhas de peças de exército, dados e uma caveira sobre Jibuti.",
  i18n = {
    en = {
      title    = "The Corporate Tomorrow",
      subtitle = "A Cyberpunk RED setting · 2126",
      genre    = "Corporate dystopia",
      blurb    = "In 2126 the world did not end: it was bought in instalments. Corporations became countries, governments became leftovers, and a spoon became a symbol of terrorism.",
      period   = "2126",
      place    = "The whole world · Brasília",
      kicker   = "A grounded Cyberpunk RED setting · The world in 2126 · An opening adventure in Brasília",
      cover_title = "The Corporate<br>Tomorrow",
      banner_alt = "Pixel-art world map on a red game board: each continent painted in a corporation's colour, with piles of army pieces, dice and a skull over Djibouti.",
    },
  },
  labels   = true,           -- every page is tagged History / Fiction / History + Fiction
  spine    = { color = "#8e1b1b", light = "#b5302a", band = "#e0b23a", ink = "#f3e6d0",
               w = 42, h = 176, emblem = true },
  magic    = "#e0473b",      -- the colour of the fire when this book is in the circle
  cover    = "cover.html",   -- generated by tools/cover.lua
  contrib_page = "board",
  open_contributions = true,

  contrib = {
    chapters = {
      intro        = { "idea" },
      history      = { "timeline-event", "idea" },
      board        = { "estemp", "idea" },
      regests      = { "regest", "place" },
      collaborator = { "idea", "rule" },
      spoon        = { "idea" },
      resistance   = { "faction", "idea" },
      rules        = { "rule", "implant" },
      characters   = { "runner" },
      adventure    = { "scene", "npc", "handout" },
      appendix     = { "source" },
    },
    pages = {
      ["timeline"]      = { "timeline-event" },
      ["scenario-flow"] = { "scene" },
      ["implants"]      = { "implant" },
      ["what-next"]     = { "scene", "idea" },
      ["handouts"]      = { "handout" },
      ["about"]         = false,
    },
  },
}
