-- Interface text that belongs to this book only (Cyberpunk RED sheets, the
-- board, the boxes). Generic book-page text comes from lib/book_strings.lua.

return {
  pt = {
    footer = "<em>%s</em> — um cenário original para Cyberpunk RED por %s. Gerado a partir de dados em Lua com <code>build.lua</code>. Cyberpunk e Cyberpunk RED são marcas da R. Talsorian Games; este é um material de fã, não oficial.",
    title_suffix = " — um cenário de Cyberpunk RED",
    boxes = { read = "Leia em voz alta", gm = "Nota do Mestre", real = "No mundo real", ad = "Mensagem do patrocinador", rule = "Regra pé no chão" },
    glance = {
      { "Sistema", "Cyberpunk RED, numa versão pé no chão (capítulo VIII)" },
      { "Jogadores", "3 a 5 (4 personagens prontos incluídos)" },
      { "Época", "2126, cem anos depois de hoje" },
      { "Formato", "Cenário de mundo inteiro + o começo de uma aventura, sem final escrito" },
      { "Tom", "Distopia corporativa realista, burocrática e cinza" },
    },
    start = "Começar a ler", play = "Ir para a aventura",
    stats = { INT = "INT", REF = "REF", DEX = "DES", TECH = "TEC", COOL = "FRI", WILL = "VON", LUCK = "SOR", MOVE = "MOV", BODY = "COR", EMP = "EMP" },
    stat_names = { INT = "Inteligência", REF = "Reflexos", DEX = "Destreza", TECH = "Técnica", COOL = "Frieza", WILL = "Vontade", LUCK = "Sorte", MOVE = "Movimento", BODY = "Corpo", EMP = "Empatia" },
    derived = { HP = "Pontos de Vida", SW = "Gravemente Ferido", DS = "Teste de Morte", HUM = "Humanidade", EMPNOW = "EMP atual" },
    derived_short = { HP = "PV", SW = "Grav. Ferido", DS = "T. Morte", HUM = "Hum." },
    roles = { solo = "Solo", tech = "Tech", medtech = "Medtech", nomad = "Nômade", media = "Mídia", exec = "Executivo",
              fixer = "Fixer", security = "Segurança Patrimonial", agitator = "Agitador", operator = "Operador de Sistemas" },
    sheet = {
      quote = "Fala", origin = "De onde vem", motivation = "Por que está aqui", hook = "Gancho pessoal",
      stats = "Atributos", stats_hint = "Pacote Completo: 62 pontos, de 2 a 8 cada. O build confere a soma.",
      derived_hint = "PV, Gravemente Ferido, Teste de Morte e Humanidade são calculados pelo <code>build.lua</code>.",
      skills = "Perícias principais", skills_head = { "Perícia", "Atributo", "Nível", "Base" },
      implants = "Implantes", implants_head = { "Implante", "Titular", "Perda de Humanidade" },
      no_implants = "Nenhum. Carne de fábrica.",
      weapons = "Armas", weapons_head = { "Arma", "Dano", "CdT", "Observação" },
      armor = "Armadura (PB)", head = "Cabeça", body = "Corpo",
      gear = "Equipamento", threads = "Fios para puxar",
    },
    npc = { stats = "Atributos", hp = "PV", sw = "Grav. Ferido", ds = "T. Morte", armor = "Armadura (PB)",
            head = "Cabeça", body = "Corpo", weapons = "Armas", skills = "Perícias (base)", implants = "Implantes", notes = "Notas" },
    implants_head = { "Implante", "Perda de Humanidade", "Custo", "Titular padrão", "Exige Tolerina", "O que faz" },
    yes = "Sim", no = "Não",
    owner = { employer = "O empregador", none = "Ninguém (clandestino)", aegis = "Aegis-Med", ["kuro-tech"] = "Kuro-Tech", omniterra = "OmniTerra" },
    estemps_head = { "ESTEMP", "Território", "Peças no tabuleiro" },
    regests_head = { "Nº", "País", "O que sobrou" },
    tiers = { major = "Uma das cinco grandes", minor = "Estado Empresarial menor" },
    sea_region = "Todos os oceanos",
    map_caption = "Cada cor é um Estado Empresarial. O mar é da Thalassa Corp, e as peças vermelhas dela estão em todos os oceanos. Os quadradinhos numerados são os REGESTs (a Europa Ocidental aparece ampliada no canto). Passe o mouse num REGEST para ver o nome. No celular, arraste o mapa para o lado.",
    open_scene = "Em aberto",
    flow_lede = "%d cenas. A aventura de abertura não tem final escrito: as cenas marcadas <strong>Em aberto</strong> são onde a história de vocês começa a andar sozinha. O build confere que toda cena pode ser alcançada e que todo caminho chega a uma cena em aberto.",
    flow_caption = "Cada caixa é uma cena; clique para ir até ela. As caixas vermelhas estão em aberto.",
    localmap_caption = "A represa do Descoberto, na divisa entre o REGEST de Brasília e o território da OmniTerra. Fora de escala.",
    char_label = "Personagem pronto",
    rof = "CdT",
    map_full = "Abrir o mapa em tela cheia →", map_title = "O tabuleiro", map_back = "← Voltar ao livro",
  },

  en = {
    footer = "<em>%s</em> — an original Cyberpunk RED setting by %s. Built from Lua data with <code>build.lua</code>. Cyberpunk and Cyberpunk RED are trademarks of R. Talsorian Games; this is unofficial fan content.",
    title_suffix = " — a Cyberpunk RED setting",
    boxes = { read = "Read aloud", gm = "GM note", real = "In the real world", ad = "A word from our sponsor", rule = "Grounded rule" },
    glance = {
      { "System", "Cyberpunk RED, in a grounded version (chapter VIII)" },
      { "Players", "3 to 5 (4 pre-generated characters included)" },
      { "Era", "2126, a hundred years from now" },
      { "Format", "A whole-world setting + the start of an adventure, with no written ending" },
      { "Tone", "Realistic corporate dystopia: bureaucratic and grey" },
    },
    start = "Start reading", play = "Go to the adventure",
    stats = { INT = "INT", REF = "REF", DEX = "DEX", TECH = "TECH", COOL = "COOL", WILL = "WILL", LUCK = "LUCK", MOVE = "MOVE", BODY = "BODY", EMP = "EMP" },
    stat_names = { INT = "Intelligence", REF = "Reflexes", DEX = "Dexterity", TECH = "Technique", COOL = "Cool", WILL = "Willpower", LUCK = "Luck", MOVE = "Movement", BODY = "Body", EMP = "Empathy" },
    derived = { HP = "Hit Points", SW = "Seriously Wounded", DS = "Death Save", HUM = "Humanity", EMPNOW = "Current EMP" },
    derived_short = { HP = "HP", SW = "Ser. Wounded", DS = "Death Save", HUM = "Hum." },
    roles = { solo = "Solo", tech = "Tech", medtech = "Medtech", nomad = "Nomad", media = "Media", exec = "Exec",
              fixer = "Fixer", security = "Corporate Security", agitator = "Agitator", operator = "Systems Operator" },
    sheet = {
      quote = "Says", origin = "Where they come from", motivation = "Why they are here", hook = "Personal hook",
      stats = "Stats", stats_hint = "Complete Package: 62 points, 2 to 8 each. The build checks the total.",
      derived_hint = "HP, Seriously Wounded, Death Save and Humanity are computed by <code>build.lua</code>.",
      skills = "Key skills", skills_head = { "Skill", "Stat", "Level", "Base" },
      implants = "Implants", implants_head = { "Implant", "Owner", "Humanity Loss" },
      no_implants = "None. Factory flesh.",
      weapons = "Weapons", weapons_head = { "Weapon", "Damage", "ROF", "Note" },
      armor = "Armour (SP)", head = "Head", body = "Body",
      gear = "Gear", threads = "Threads to pull",
    },
    npc = { stats = "Stats", hp = "HP", sw = "Ser. Wounded", ds = "Death Save", armor = "Armour (SP)",
            head = "Head", body = "Body", weapons = "Weapons", skills = "Skills (base)", implants = "Implants", notes = "Notes" },
    implants_head = { "Implant", "Humanity Loss", "Cost", "Default owner", "Needs Tolerin", "What it does" },
    yes = "Yes", no = "No",
    owner = { employer = "The employer", none = "Nobody (black market)", aegis = "Aegis-Med", ["kuro-tech"] = "Kuro-Tech", omniterra = "OmniTerra" },
    estemps_head = { "ESTEMP", "Territory", "Pieces on the board" },
    regests_head = { "No.", "Country", "What is left" },
    tiers = { major = "One of the big five", minor = "Lesser corporate state" },
    sea_region = "Every ocean",
    map_caption = "Each colour is a corporate state. The sea belongs to Thalassa Corp, whose red pieces sit in every ocean. Numbered squares are the REGESTs (Western Europe is enlarged in the corner). Hover a REGEST to see its name. On a phone, drag the map sideways.",
    open_scene = "Open",
    flow_lede = "%d scenes. The opening adventure has no written ending: scenes marked <strong>Open</strong> are where your table's story starts to run on its own. The build checks that every scene can be reached and that every path arrives at an open scene.",
    flow_caption = "Each box is a scene; click one to jump to it. Red boxes are open.",
    localmap_caption = "The Descoberto reservoir, on the border between the Brasília REGEST and OmniTerra territory. Not to scale.",
    char_label = "Pre-generated character",
    rof = "ROF",
    map_full = "Open the map full screen →", map_title = "The board", map_back = "← Back to the book",
  },
}
